name: Run Terraform from Front

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        type: choice
        default: 'dev'
        options: [dev, prod]
      action:
        description: 'Terraform action'
        required: true
        type: choice
        default: 'plan'
        options: [plan, apply, destroy]
  push:
    branches:
      - terraform-implementation
      - dev

jobs:
  trigger-terraform:
    uses: Letterbox-discovery-recommendations/terraform/.github/workflows/terraform-deploy.yml@main
    with:
      environment: ${{ inputs.environment || 'dev' }}
      action: ${{ 
        (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/terraform-implementation') 
        && 'apply' 
        || (inputs.action || 'plan') 
        }}
      aws_region: us-east-2

    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      INFRA_REPO_TOKEN: ${{ secrets.INFRA_REPO_TOKEN }}
