name: Run Terraform from Front

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        type: choice
        options: [dev, prod]
      action:
        description: 'Terraform action'
        required: true
        type: choice
        default: 'plan'
        options: [plan, apply, destroy]
  
  push:
    branches:
      - terraform-implementation

jobs:
  trigger-terraform:
    runs-on: ubuntu-latest 
    environment: aws-terraform
    uses: Letterbox-discovery-recommendations/terraform/.github/workflows/terraform-deploy.yml@main
    with:
      environment: ${{ inputs.environment || 'dev' }}
      action: ${{ inputs.action || 'plan' }}
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
